### ISSUE TITLE
Missing 'Objects' and 'Rules' in Access Control Concepts

### ISSUE THREAD

**Issue by XMLSDK** [cyberfascinate/ISC2-CC-Study-Material#1]
After `Access is based on three elements:  `, there is only 'Subjects' but missing 'Objects' and 'Rules'
https://github.com/cyberfascinate/ISC2-CC-Study-Material/blob/main/Notes/Access%20Control%20Concepts/Access%20Control%20Concepts.md

**Comment by cyberfascinate** [comment]
Soon i will update

**Comment by abuloollaith** [comment]
Is it updated?

**Comment by Nocturne107** [comment]
> Is it updated?

Did we get an update on this issue
