### ISSUE TITLE
Links of flash card are expired

### ISSUE THREAD

**Issue by yo-ga** [cyberfascinate/ISC2-CC-Study-Material#4]
All links in Flash Card document are expired. Maybe we need to replace or renew the link.

**Comment by cyberfascinate** [comment]
Yes , We need too

**Comment by abuloollaith** [comment]
Thank you for the content and everything. Any update on the flashing cards?

**Comment by rashmidahiya** [comment]
[This](https://quizlet.com/ISC2Education/folders/certification-in-cybersecurity-1st-edition/sets) might be helpful :)

**Comment by abuloollaith** [comment]
Thank YouSincere,LaithOn 24 Jul 2023, at 9:29 PM, Rashmi Dahiya ***@***.***> wrote:﻿
This might be helpful :)

**Comment by Nocturne107** [comment]
Hey did you ever get around to getting the flash cards up and running?

**Comment by cyberfascinate** [comment]
https://cloud.connect.isc2.org/cc-flashcards
https://quizlet.com/779965480/isc2-certified-in-cybersecurity-exam-prep-flash-cards/
https://cloud.connect.isc2.org/cc-quiz
